"""
Takes raw game screenshot data and processes, shrinks, and cleans up the
"image tiles" for the various rooms for use in the map.

Also generates mapData.js which includes info like which items are in a room where
and how the map tiles line up with the coordinate system.
"""

import glob
import os
import sys
import json
import logging
from os.path import exists

import TileHandler
import roomInfo

outputFolder = os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + "/Web/MapTiles"

mapData = {"rooms": {}}

def readMapData():
	global mapData
	try:
		with open(outputFolder + "/../mapData.js", "rt", encoding='utf-8') as f:
			contents = f.read()
			data = contents.split("window.mapData =")[1]
			mapData = json.loads(data)
	except:
		logging.exception("Failed to read existing mapData.js")



def writeMapData():
	with open(outputFolder + "/../mapData.js", "wt", encoding='utf-8') as f:
		f.write("//This file is automatically generated by processData.py, don't edit\n")
		f.write("window.mapData = ")
		json.dump(mapData, f, indent=2)

def getTileNames():
	# TileHandler.DEBUG_IMAGE = True
	# yield "Fungus2_26"
	# return


	for file in glob.glob("*.json"):
		tileName = file[:-5]

		if tileName == "MapData": continue
		# if exists(outputFolder + "/" + tileName + ".webp"):
		# 	continue

		yield tileName

if __name__ == "__main__":
	if len(sys.argv) <= 1:
		print("Usage: processData.py PATH_TO_DATA")
		sys.exit(1)

	roomInfo.loadData()

	os.chdir(sys.argv[1])

	readMapData()

	for tile in sorted(getTileNames()):
		print("Looking at", tile)
		handler = TileHandler.TileHandler(tile)

		if not exists(outputFolder + "/" + tile + ".webp") or TileHandler.DEBUG_IMAGE:
			handler.process()

		roomData = handler.getData()
		# print("room data", tile, repr(roomData))
		mapData["rooms"][tile] = roomData

	writeMapData()

	print("Done")
