//This file is automatically generated by builddata.py, don't edit
using System.Collections.Generic;

namespace TangledMapView.HollowKnight {
public class MapData {

	public static Dictionary<string, string> areas = new Dictionary<string, string> {
		{"Abyss", "Ancient Basin"},
		{"Cliffs", "Howling Cliffs"},
		{"Crossroads", "Forgotten Crossroads"},
		{"Deepnest", "Deepnest"},
		{"Deepnest_East", "Kingdom's Edge"},
		{"FogCanyon", "Fog Canyon"},
		{"Fungus1", "Greenpath"},
		{"Fungus2", "Fungal Wastes"},
		{"Fungus3", "Queen's Gardens"},
		{"Hive", "The Hive"},
		{"Mines", "Crystal Peak"},
		{"RestingGrounds", "Resting Grounds"},
		{"Room", "Room"},
		{"Ruins1", "City of Tears"},
		{"Ruins2", "City of Tears"},
		{"Town", "Dirtmouth"},
		{"Waterways", "Royal Waterways"},
		{"White_Palace", "White Palace"},

	};

}
}
